project_name: juno-agent

builds:
  - main: ./cmd/juno-agent
    id: juno-agent
    binary: juno-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch: [amd64]
    ldflags:
      - -X github.com/douyu/jupiter/pkg.buildAppVersion={{.Version}}
      - -X github.com/douyu/jupiter/pkg.buildTime={{.Date}}
      - -X github.com/douyu/jupiter/pkg.buildUser=goreleaser
